### ISSUE TITLE
Map doesn't load with single date

### ISSUE THREAD

**Issue by NateMeyer** [Rycieos/factorio-leaflet-maps#2]
If there is only a single entry in the array in dates.json, the map does not display.

**Comment by Rycieos** [comment]
I'm not able to recreate this. A JSON file with only this:
```json
[
  "2020-04-11"
]
```
loads correctly. Are you sure you didn't have a comma (`,`) trailing the only value? JSON is picky about that.

However, this has made me realize that we shouldn't show the date selection bar if there is only one value in the array.

**Comment by NateMeyer** [comment]
Went back and could not reproduce. I had checked that the json looked right, but must have missed something.
